services:
  test-api:
    image: webdevops/php-apache-dev:8.3-alpine
    container_name: test-api
    working_dir: /app
    ports:
      - "${API_EXT_PORT:-80}:80"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      WEB_DOCUMENT_INDEX: "index.php"
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: 1
      XDEBUG_CLIENT_HOST: host.docker.internal
  test-db:
    image: postgres:16
    container_name: test-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-test_db}
      POSTGRES_USER: ${DB_USER:-test_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-test_password}
    ports:
      - "${DB_EXT_PORT:-5432}:5432"
    volumes:
      - ./docker/db/postgres_data:/var/lib/postgresql/data
      - ./docker/db/docker-entrypoint-initdb:/docker-entrypoint-initdb.d